# NumPy 

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

In [1]:
import numpy as np

In [2]:
my_list = [1,2,3]
one_darray = np.array(my_list)

In [3]:
print(one_darray)

[1 2 3]


In [4]:
print(one_darray.dtype)

int64


In [5]:
print(one_darray.shape)

(3,)


In [6]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
two_darray = np.array(my_matrix)
print(two_darray)
print(two_darray.dtype)
print(two_darray.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
int64
(3, 3)


## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

In [7]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### zeros and ones

Generate arrays of zeros or ones

In [10]:
np.zeros(3)

array([0., 0., 0.])

In [11]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.ones(3)

array([1., 1., 1.])

In [14]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## Random 

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [15]:
np.random.randint(1,100)

24

In [16]:
np.random.randint(1,100,10)

array([50, 21, 37, 98, 99, 31, 93, 32,  1, 70])

In [17]:
x = np.random.randint(1,100,9)
print(x)

[15 47 80  9  2 66  4 31 80]


## Reshape
Returns an array containing the same data with a new shape.

In [18]:
x.reshape(3,3)

array([[15, 47, 80],
       [ 9,  2, 66],
       [ 4, 31, 80]])

# NumPy Indexing and Selection

In this lecture we will discuss how to select elements or groups of elements from an array.

In [19]:
#Creating sample array
arr = np.arange(0,11)

In [20]:
#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [21]:
#Get a value at an index
arr[8]

8

In [22]:
#Get values in a range
arr[0:5]

array([0, 1, 2, 3, 4])

## Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [23]:
#Setting a value with index range (Broadcasting)
arr[0:5]=100

In [24]:
#Show
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [25]:
lst = [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]

In [ ]:
lst[0:5] = 100

## Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. I recommend usually using the comma notation for clarity.

In [26]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [27]:
#Indexing row
arr_2d[1]

array([20, 25, 30])

In [28]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

### Fancy Indexing

Fancy indexing allows you to select entire rows or columns out of order,to show this, let's quickly build out a numpy array:

In [29]:
arr2d = np.zeros((10,10))

In [30]:
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [31]:
#Set up array

for i in range(10):
    arr2d[i]= i 
    
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

## Selection

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [32]:
import numpy as np
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [34]:
arr[arr > 4]

array([ 5,  6,  7,  8,  9, 10])

# NumPy Operations

## Arithmetic

You can easily perform array with array arithmetic, or scalar with array arithmetic. Let's see some examples:

In [35]:
arr = np.arange(0,10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
arr + arr

In [ ]:
arr * arr

In [ ]:
arr - arr

In [ ]:
# Warning on division by zero, but not an error!
# Just replaced with nan
arr/arr

In [ ]:
arr**3